    //Handling Errors with try and catch
try {
    test();
} catch (error) {
    console.log(errpr);
    
} finally {
    console.log('Finally!');
}


